name: test
on:
  push:
    branches:
      - '*'
  pull_request:
permissions:
  contents: write
jobs:
  test:
    env:
      GO111MODULE: "on"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Install nats-server
        uses: aricart/install-binary@v1.0.0
        with:
          repo: nats-io/nats-server
          name: nats-server
          cache: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true

      - name: Tests
        run: |
          task test

      - name: Upload coverage
        uses: coverallsapp/github-action@v2
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{ matrix.module }}
          file: ./coverage.out
